### ISSUE TITLE
Create a cool README.md file

### ISSUE THREAD

**Issue by exler** [exler/logey#1]
The project is not very complicated, so there is not much to write about. But it would be nice to see some design enhancements, maybe some badges, markdown styling, information about license and such. I'm very open to ideas.

**Comment by larsmhar** [comment]
Could I help with this?

**Comment by thomasstep** [comment]
I would also like to help with this.

**Comment by exler** [comment]
@larsmhar and @thomasstep feel free to work on it.

**Comment by sarthak268** [comment]
Please assign me this

**Comment by exler** [comment]
@sarthak268 I unfortunately cannot assign you to it, but I will gladly accept your pull request.

**Comment by exler** [comment]
We are still in a dire need of a good README file! Anyone feeling like doing it?

**Comment by exler** [comment]
Thanks @AlwaysHungrie. I will close this issue now, but you can still contribute to our README!
