### ISSUE TITLE
Enhancement: Support more Virtual Key Codes

### ISSUE THREAD

**Issue by xorz57** [exler/logey#10]
Take a look at [this](https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx) page.

**Comment by exler** [comment]
To be honest, I added every Virtual Key I think was useful. Unless I add some kind of detection in which window the user is, more Virtual Key Codes are unnecessary.

**Comment by xorz57** [comment]
@exler

> Unless I add some kind of detection in which window the user is, more Virtual Key Codes are unnecessary.

Should we reopen this issue now that the window detection is done?

**Comment by exler** [comment]
I thought about it and I think that besides maybe 3 or 4 additional key codes, rest of them like mouse buttons are useless, even though you know what window the user is in, you don't know where he clicks or what is the purpose of those key clicks. I'm gonna keep it closed, maybe with next update I will add those that I think will be useful.

**Comment by xorz57** [comment]
@exler Nice!
