### ISSUE TITLE
Got Question

### ISSUE THREAD

**Issue by Lilantboy** [exler/logey#17]
Where did you learn to use functions in the windows.h file ?

**Comment by exler** [comment]
If you meant how do I know what does the library do, you can find all that in the official Microsoft documentation [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383745(v=vs.85).aspx) and [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ff818516(v=vs.85).aspx).
