### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by exler** [exler/logey#2]
I used some hacks around the compiler warnings so it would be nice if someone more experienced could clean up the code and maybe rewrite it in a more effective way.

**Comment by exler** [comment]
Thanks to @thomasstep the code is now cleaner, but I believe there is always room for improvement! If anyone has an idea how to make the code slicker, feel free to work on it!

**Comment by exler** [comment]
Thanks @thomasstep and @xorz57 for all the hard work!

**Comment by xorz57** [comment]
@exler You're welcome!
