### ISSUE TITLE
Make the log file prettier

### ISSUE THREAD

**Issue by exler** [exler/logey#4]
Currently there is no way to distinguish sessions of keylogger in the log file. Prettify it with new lines, session timestamps and maybe some info about the keylogger. Example of information at the top of every session output: 

```
logey --- a Windows keylogger
author: exler
license: MIT

timestamp: %d-%m-%y %H:%M:%S
```

**Comment by Jerrgree** [comment]
I'll tackle this

**Comment by xorz57** [comment]
A cool addition would be to keep track of the active window name when keys are typed

**Comment by Jerrgree** [comment]
That would be easy enough.

**Comment by exler** [comment]
@Jerrgree I merged your pull request. Is anyone interested in adding the tracking of active window name, as @xorz57 suggested?

**Comment by Jerrgree** [comment]
Yeah, I'll get that too

**Comment by exler** [comment]
Nice! It's done.
