### ISSUE TITLE
Question: Which language would you want to use? C or C++?

### ISSUE THREAD

**Issue by xorz57** [exler/logey#7]
I see that you are using the .cpp file extension but you are writing in C instead of C++.
Which language do you intend to use for this project?

**Comment by exler** [comment]
I intended to use C++, because that's what's I'm trying to improve. Might be wrong tutorials and guides I tried to follow 😕

**Comment by xorz57** [comment]
@exler Yeah, I had the same problem when I took the C++ course in the university because they taught us bad practices using a lot of stuff from C instead of C++. You can take a look at [this](https://www.amazon.com/Primer-5th-Stanley-B-Lippman/dp/0321714113) book. Its really good!

**Comment by exler** [comment]
@xorz57 I'll have a look at it when I have some time to spare. Thanks!

**Comment by xorz57** [comment]
@exler One last question. I guess the keylogger will work only on windows OS, am I right?

**Comment by exler** [comment]
@xorz57 That's right. Everything was written with Windows in mind.

**Comment by xorz57** [comment]
I am currently rewriting the project in C++ and putting everything in one place inside a visual studio project keeping it clean to make the development easier. I hope the final be pleasant 🍺.
