### ISSUE TITLE
Feature: You are propably going to need a build system

### ISSUE THREAD

**Issue by xorz57** [exler/logey#8]
My suggestion is that you should use [cmake](https://cmake.org/) as a build system.
This will make development faster and easier.

**Comment by exler** [comment]
Yeah, I know. It's just that it is such a simple project that I didn't bother creating a Makefile and I was using my IDE to compile. If you want, you can create one :smiley:

**Comment by xorz57** [comment]
Would you mind if I make a clean Visual Studio Project Instead?

**Comment by exler** [comment]
Not at all, if the result is good 😄
